version: '3'
services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=cookbook
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:${ADMINER_PORT:-8080}
  backend:
    image: node:21
    restart: unless-stopped
    working_dir: /opt/app
    command: npm run dev -w backend
    volumes:
      - .:/opt/app
    ports:
      - 4000:4000
  frontend:
    image: node:21
    restart: unless-stopped
    working_dir: /opt/app
    command: npm run start -w frontend
    volumes:
      - .:/opt/app
    ports:
      - 3000:3000
    environment:
      - BACKEND_URL=http://backend:4000
volumes:
  postgres_data:
