/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface Category {
  createdAt: Generated<Timestamp>
  id: Generated<number>
  name: string
  updatedAt: Generated<Timestamp>
}

export interface Ingredient {
  amount: string
  createdAt: Generated<Timestamp>
  groupId: number
  id: Generated<number>
  name: string
  order: number
  unit: string
  updatedAt: Generated<Timestamp>
}

export interface IngredientGroup {
  createdAt: Generated<Timestamp>
  id: Generated<number>
  name: string | null
  recipeId: number
  updatedAt: Generated<Timestamp>
}

export interface Recipe {
  createdAt: Generated<Timestamp>
  description: string | null
  id: Generated<number>
  instructions: string | null
  name: string
  updatedAt: Generated<Timestamp>
}

export interface RecipeCategory {
  categoryId: number
  recipeId: number
}

export interface DB {
  Category: Category
  Ingredient: Ingredient
  IngredientGroup: IngredientGroup
  Recipe: Recipe
  RecipeCategory: RecipeCategory
}
