/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface _CategoryToRecipe {
  A: number
  B: number
}

export interface _PrismaMigrations {
  applied_steps_count: Generated<number>
  checksum: string
  finished_at: Timestamp | null
  id: string
  logs: string | null
  migration_name: string
  rolled_back_at: Timestamp | null
  started_at: Generated<Timestamp>
}

export interface Category {
  createdAt: Generated<Timestamp>
  id: Generated<number>
  name: string
  updatedAt: Timestamp
}

export interface Ingredient {
  amount: string
  createdAt: Generated<Timestamp>
  groupId: number
  id: Generated<number>
  name: string
  order: number
  unit: string
  updatedAt: Timestamp
}

export interface IngredientGroup {
  createdAt: Generated<Timestamp>
  id: Generated<number>
  name: string | null
  recipeId: number
  updatedAt: Timestamp
}

export interface Recipe {
  createdAt: Generated<Timestamp>
  description: string | null
  id: Generated<number>
  instructions: string | null
  name: string
  updatedAt: Timestamp
}

export interface DB {
  _CategoryToRecipe: _CategoryToRecipe
  _prisma_migrations: _PrismaMigrations
  Category: Category
  Ingredient: Ingredient
  IngredientGroup: IngredientGroup
  Recipe: Recipe
}
